




const stateAbbreviations = {
    // 2-letter abbreviations
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",

    // 3-letter abbreviations
    "ALA": "Alabama",
    "AKS": "Alaska",
    "ARS": "Arizona",
    "ARK": "Arkansas",
    "CAL": "California",
    "COL": "Colorado",
    "CON": "Connecticut",
    "DEL": "Delaware",
    "FLA": "Florida",
    "GEA": "Georgia",
    "HAW": "Hawaii",
    "IDA": "Idaho",
    "ILL": "Illinois",
    "IND": "Indiana",
    "IOW": "Iowa",
    "KAN": "Kansas",
    "KYT": "Kentucky",
    "LOU": "Louisiana",
    "MAI": "Maine",
    "MAR": "Maryland",
    "MAS": "Massachusetts",
    "MIC": "Michigan",
    "MIN": "Minnesota",
    "MIS": "Mississippi",
    "MIZ": "Missouri",
    "MON": "Montana",
    "NEB": "Nebraska",
    "NEV": "Nevada",
    "NEW": "New Hampshire",
    "NEJ": "New Jersey",
    "NMX": "New Mexico",
    "NYC": "New York",
    "NOR": "North Carolina",
    "NDA": "North Dakota",
    "OHI": "Ohio",
    "OKL": "Oklahoma",
    "ORE": "Oregon",
    "PEN": "Pennsylvania",
    "RHI": "Rhode Island",
    "SCA": "South Carolina",
    "SDA": "South Dakota",
    "TEN": "Tennessee",
    "TEX": "Texas",
    "UTA": "Utah",
    "VER": "Vermont",
    "VIR": "Virginia",
    "WAS": "Washington",
    "WVA": "West Virginia",
    "WIS": "Wisconsin",
    "WYO": "Wyoming",
};
